### ISSUE TITLE
Basic Auth instead of webFlow for github authentication?

### ISSUE THREAD

**Issue by maulindesai** [brijeshshah13/OpenCI#7]
Hi, 
should we include basic-authentication in OpenCI project. so user need not leave the current application flow.

**Comment by brijeshshah13** [comment]
@maulindesai Actually, I don't plan on implementing it because of the following reasons: 

- First of all we won't be able to use Basic Authentication even if we wanted to because we need to intercept and retrieve the `code` from the callback url, which will be used to exchange it for the GitHub `access_token`, which will be in turn used to exchange it for the Travis Public and Private `access_token`s.

- Second thing, GitHub WebFlow is far more secure than Basic Authentication.

You can pitch in ideas for the UI of the rest of the app :) Also, please close this issue if you find the answer up to the mark.
